services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 5173:5173
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 3000:3000
